# What is R?
A statistical programming language

# What is Rstudio?

It is a free,open source integrated development environment(IDE) for R
RStudio helps to keep R more organized and it adds more functionality to it

# R Markdown

It allows u to embed R cde and R output directly into documents,pdf,HTML,Word etc

In [1]:
x = 12 + 6.0
print(x)

[1] 18


In [3]:
#we can also assign the value using arrow sign
y <- 12 + 6.0
print(y)

[1] 18


In [4]:
# to see list of variables stored in the memory
ls()

[1] "x" "y"

In [5]:
# To remove variable y from the memory
rm(y)

In [6]:
ls()

[1] "x"

In [7]:
x.1  <- 1
print(x)

[1] 18

In [9]:
x = 5/3
print(x)

[1] 1.666667


In [10]:
x = 5^2
print(x)

[1] 25


In [11]:
y=sqrt(1/2)
print(y)

[1] 0.7071068


In [12]:
z=log(16)
print(z)

[1] 2.772589


In [13]:
z=log2(16)
print(z)

[1] 4


In [14]:
x= abs(-1)
print(x)

[1] 1


In [16]:
x = 1
print(x)

[1] 1


In [17]:
x = c(1,3,5,7,9)
print(x)

[1] 1 3 5 7 9


In [18]:
x = c('abcd','efgh','ijkl')
print(x)

[1] "abcd" "efgh" "ijkl"


In [19]:
# To print values from 2 to 7 
#remember 7 bhi print hoga(whereas python me 7 nahi aata
print(2:7)

[1] 2 3 4 5 6 7


In [20]:
#To print sequence  of numbers
seq(from = 1,to = 7,by =1) #by means step size

[1] 1 2 3 4 5 6 7

In [21]:
seq(from = 1,to = 7,by =1/3)

[1] 1.000000 1.333333 1.666667 2.000000 2.333333 2.666667 3.000000 3.333333
 [9] 3.666667 4.000000 4.333333 4.666667 5.000000 5.333333 5.666667 6.000000
[17] 6.333333 6.666667 7.000000

In [22]:
seq(from = 1,to = 7,by = 0.25)

[1] 1.00 1.25 1.50 1.75 2.00 2.25 2.50 2.75 3.00 3.25 3.50 3.75 4.00 4.25 4.50
[16] 4.75 5.00 5.25 5.50 5.75 6.00 6.25 6.50 6.75 7.00

In [23]:
# to repeat 1 ten times
rep(1,time=10)

[1] 1 1 1 1 1 1 1 1 1 1

In [24]:
rep('Kartikay',times=5)

[1] "Kartikay" "Kartikay" "Kartikay" "Kartikay" "Kartikay"

In [25]:
rep(1:4,times=5)

[1] 1 2 3 4 1 2 3 4 1 2 3 4 1 2 3 4 1 2 3 4

In [27]:
rep(seq(from=2,to=5,by=.25),times=5)

[1] 2.00 2.25 2.50 2.75 3.00 3.25 3.50 3.75 4.00 4.25 4.50 4.75 5.00 2.00 2.25
[16] 2.50 2.75 3.00 3.25 3.50 3.75 4.00 4.25 4.50 4.75 5.00 2.00 2.25 2.50 2.75
[31] 3.00 3.25 3.50 3.75 4.00 4.25 4.50 4.75 5.00 2.00 2.25 2.50 2.75 3.00 3.25
[46] 3.50 3.75 4.00 4.25 4.50 4.75 5.00 2.00 2.25 2.50 2.75 3.00 3.25 3.50 3.75
[61] 4.00 4.25 4.50 4.75 5.00

In [28]:
rep(c('male','female'),times=5)

[1] "male"   "female" "male"   "female" "male"   "female" "male"   "female"
 [9] "male"   "female"

In [29]:
x=1:5

In [30]:
# to add 10 to every value of x
x+10

[1] 11 12 13 14 15

In [31]:
x=x-10
print(x)

[1] -9 -8 -7 -6 -5


In [32]:
x=1:5
x*10

[1] 10 20 30 40 50

In [33]:
x/10

[1] 0.1 0.2 0.3 0.4 0.5

In [34]:
#If the 2 vectors are of same length ,then we may add/subtract/multiply/divide corresponding elements
x=1:5
y=6:10

x+y

[1]  7  9 11 13 15

In [35]:
x-y

[1] -5 -5 -5 -5 -5

In [36]:
x*y

[1]  6 14 24 36 50

In [38]:
x/y

[1] 0.1666667 0.2857143 0.3750000 0.4444444 0.5000000

In [46]:
y

[1]  6  7  8  9 10

In [47]:
#To extract 2nd element
y[2]

[1] 7

In [48]:
#To extract all the elements except 4th element
y[-4]

[1]  6  7  8 10

In [49]:
 #To extract first 3 elements
y[1:3]

[1] 6 7 8

In [50]:
#to print first and 5th element
y[c(1,5)]

[1]  6 10

In [52]:
#to print all the elements except first and 5th element
y[-c(1,5)]

[1] 7 8 9

In [53]:
# extract all the elements less than 8
y[y<8]

[1] 6 7

In [54]:
matrix(c(1,2,3,4,5,6,7,8,9),nrow=3,byrow=TRUE)    
# byrow=TRUE means elements are added row wise

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

In [55]:
matrix(c(1,2,3,4,5,6,7,8,9),nrow=3,byrow=FALSE)    
# byrow=FALSE means elements are added column wise

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [56]:
mat = matrix(c(1,2,3,4,5,6,7,8,9),nrow=3,byrow=TRUE) 

In [57]:
print(mat)

     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9


In [58]:
# to extract element from row =1 1 column=2
mat[1,2]

[1] 2

In [59]:
#from row = 1 and 3 ,column = 2
mat[c(1,3),2]

[1] 2 8

In [60]:
#2nd row
mat[2,]

[1] 4 5 6

In [61]:
#2nd column
mat[,2]

[1] 2 5 8

In [62]:
mat*10

[,1] [,2] [,3]
[1,] 10   20   30  
[2,] 40   50   60  
[3,] 70   80   90